name: Update repository index
on:
  push:
    branches:
      - main
    paths:
      - "*.tgz"

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v3
        with:
          version: '3.11.1'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Generate Index
        id: index
        run: |
          helm repo index .

      - name: Commit & Push
        run: |
          git config user.name hcloud-bot
          git config user.email github-bot@hetzner-cloud.de

          git add index.yaml
          git commit -m "chore: update repository index"

          git push origin
